server:
  address: 0.0.0.0
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
security:
  jwt:
    token:
      secret-key: ${PROJECT_NAME_HERE_SECRET_KEY}
      expire-length: ${EXPIRE_LENGTH_IN_MILLISECONDS}
file:
  file-dir: ${FILE_DIR}
  fetch-url: ${FETCH_URL}
search:
  post:
    url: localhost2
    port: 9200
    scheme: http
