server:
  address: localhost
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password:
    url: jdbc:postgresql://3.34.208.67:5432/poolc?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
security:
  jwt:
    token:
      secret-key: ${PROJECT_NAME_HERE_SECRET_KEY}
      expire-length: ${EXPIRE_LENGTH_IN_MILLISECONDS}
