server:
  address: localhost
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
security:
  jwt:
    token:
      secret-key: ${PROJECT_NAME_HERE_SECRET_KEY}
      expire-length: ${EXPIRE_LENGTH_IN_MILLISECONDS}
file:
  file-dir: ${FILE_DIR}
  fetch-url: ${FETCH_URL}