server:
  address: localhost
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password:
    url: jdbc:postgresql://52.78.116.38:5432/poolc?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true